/*
A COMPANY WANTS TO CONTACT EACH OF ITSS CUSTOMERS REGARDING THE POLICY CHANGES. THEY HAVE INTERNATINAL CUSTOMERS, BUT THEIR DATABASE NOT INCLUDE COUNTRY CODES WITH THEIR PHONE NUMBERS.

THERE ARE TWO TABLES IN THE DATABASE: CUSTOMERS AND COUNTRY_CODES. THE FIRST TABLE CONTAINS DETAILS OF EVERY CUSTOMER INCLUDING CUSTOMER_ID, NAME, PHONE_NUMBER, AND COUNTRY. THE SECOND TABLE CONTAINS THE COUNTRY CODE FOR EVERY COUNTRY.

WRITE A QUERY TO RETRIEVE A LIST OF ALL CUSTOMER IDS, NAMES, AND PHONE NUMBERS, WITH THEIR COUNTRY CODE CONCATENATED EITH PHONE NUMBERS. SORT THE OUTPUT IN THE ORDER OF THEIR CUSTOMER_ID
*/
SELECT
    A.CUSTOMER_ID,
    A.NAME,
    CONCAT('+',B.COUNTRY_CODE, A.PHONE_NUMBER) AS FULL_PHONE
FROM CUSTOMERS A
INNER JOIN COUNTRY_CODES B ON A.COUNTRY = B.COUNTRY
ORDER BY A.CUSTOMER_ID
